homeWork3/blog/config/routes.rb
Rails.application.routes.draw do
  resources :articles
    resources :comments
    
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

homeWork3/blog/app/models/article.rb
class Article < ApplicationRecord
#class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
    validates :title, presence: true,
                      length: { minimum: 5 }
end

homeWork3/blog/app/models/comment.rb
class Comment < ApplicationRecord
#class Comment < ActiveRecord::Base
  belongs_to :article
validates :author, :body, presence: true,
                  length: { minimum: 1 }
end

homeWork3/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new(article: @article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

homeWork3/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
      #  format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.html { redirect_to @comment.article }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :body, :article_id)
    end
end

homeWork3/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

homeWork3/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

homeWork3/blog/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
   <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

homeWork3/blog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

homeWork3/blog/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<% @articles.each do |article| %>
  <div class="left-panel">
        <div class="col-xs-12 col-sm-6 col-lg-8">
    	    <div class="panel panel-default">
    		    <div class="panel-body">
    				<div class="col-md-12">

    						<h2><%= link_to article.title, article %></h2>
    						<p><%= article.content %></p>

              </div>
            </div>
          </div>

        </div>
      </div>
  <% end %>

</div>
<div class="container">
          <%= link_to 'New Article', new_article_path, :class=>'btn btn-default' %>
</div>

homeWork3/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<div class="container">
	<div class="row">
        <%= render 'form', article: @article %>
    </div>
</div>
<%= link_to 'Back', articles_path %>

homeWork3/blog/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="container">
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-heading">
          <strong>Title:</strong>
          <%= @article.title %>
      </div>
      <div class="panel-body">
        <strong>Content:</strong>
        <%= @article.content %>
      </div><!-- /panel-body -->
    </div><!-- /panel panel-default -->
<!-- /col-sm-5 -->

</p>

<tr class="container-fluid">
        <td><%= link_to 'Edit', edit_article_path(@article), :class=>'btn btn-default' %></td>
        <td><%= link_to 'Back', articles_path , :class=>'btn btn-default' %></td>
        <td><%= link_to 'Delete', article_path(@article), :class=>'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

<div>
<h3>Comments</h3>
    <% @article.comments.each do |comment| %>
          <div class="container">
          <div class="col-sm-5">
              <div class="panel panel-default">
              <div class="panel-heading">
            <strong><%= comment.author %></strong>

              </div>
              <div class="panel-body">
            <p><%= comment.body %></p>

            <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </div><!-- /panel-body -->
          </div><!-- /panel panel-default -->
          </div><!-- /col-sm-5 -->
        </div>
    <% end %>

<%= render 'comments/form' %>
</div>
</div>
</div>