homeWork10/todolist/config/routes.rb
Rails.application.routes.draw do
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'login_google' , to: redirect('/auth/google_oauth2'), as: 'login_google'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout' => 'sessions#destroy'


  resources :sessions , except: [:edit, :update]
  resources :users do
      resources :tasks, except: [:index] do
        member do
           patch :complete
        end
      end
  end

  root 'users#index'
end

homeWork10/todolist/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

homeWork10/todolist/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, :presence => true, uniqueness: { scope: :user,
    message: "Title exists!" }
  validates :text, presence: true

  enum priority: [:low, :regular, :top]

  after_initialize do
      if self.new_record?
        self.priority ||= :regular
      end
  end

end

homeWork10/todolist/app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  attr_accessor :full_name, :age, :total_posts, :birthdays_this_month

  email_regex = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  validates :email, :presence => true, :uniqueness => true, :format => email_regex
  validates :password, format: { with: /(?=.*?[0-9])(?=.*?[A-Za-z]).+/,
      message: "Password must contain at least one digit and one letter" }, length: { in: 6..10 }, on: :create

  validates :password, format: { with: /(?=.*?[0-9])(?=.*?[A-Za-z]).+/,
          message: "Password must contain at least one digit and one letter" }, length: { in: 6..10 }, on: :update, if: :password_digest_changed?

  has_secure_password


  #enum role: [:standard, :admin]
  require 'carrierwave'
  require 'carrierwave/orm/activerecord'
  mount_uploader :avatar, ImageUploader



  def self.find_or_create_from_auth_hash(auth)
  		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
  			user.provider = auth.provider
  			user.uid = auth.uid
  			user.first_name = auth.info.first_name
  			user.last_name = auth.info.last_name
        user.nickname = auth.info.name
  			user.email = auth.info.email
  			user.remote_avatar_url = auth.info.image
        user.password = user.password_confirmation = '1' +SecureRandom.urlsafe_base64(n=6, false)
  			user.save!
  		end
  	end

  def full_name
    [self.first_name, self.last_name].join(" ") if !self.first_name.blank? && !self.last_name.blank?
  end

  def age
    ((Time.now - self.birth_day.to_time) / 1.year.seconds).floor
  end

  def total_tasks
    self.tasks.size
  end

  def uncompleted_tasks
    self.tasks.size - self.tasks.where(completed: true).size
  end


  def birthday_today?
    return nil unless self.birth_day?
    Date.today.strftime('%m%d') == self.birth_day.strftime('%m%d')
  end

  def self.birthdays_this_month
    User.where("cast(strftime('%m', birth_day) as int) = ?", Date.today.month).limit(10).order(Arel.sql('date(birth_day)'))
  end

  def self.birthdays_today
    User.where("strftime('%m%d', birth_day) = ?", Date.today.strftime('%m%d'))
  end
end

homeWork10/todolist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :require_login, :except => [:new, :create]
skip_before_action :require_login, only: [:new, :create]
private

def require_login
  unless current_user
    flash.now.alert = 'You must be logged in to view this site'
    render ('sessions/first.html.erb')
  end
end

def authorize_admin
  redirect_to root_path, alert: 'You can view and edit only yours profile.' unless @user.id == current_user.id || @task&.user&.id == current_user.id
end

def current_user
  begin
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    session[:user_id] = nil
  end
end

helper_method :current_user

end

homeWork10/todolist/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :require_login

  def index
    #redirect_to login_path
  end

  def new
    redirect_to root_path
  end

  def create
    if request.env["omniauth.auth"].nil?

        user = User.find_by(email: params[:email].downcase)

       if user && user.authenticate(params[:password])
         session[:user_id] = user.id
         redirect_to root_path

       else
         flash.now.alert = 'Email or password is invalid'
         render :new
       end

     else

       user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
       session[:user_id] = user.id
       redirect_to root_path
     end
   end

def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Logged out!"
end

private
  def session_params
      params.require(:session).permit(:email, :password)
  end
end

homeWork10/todolist/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy, :edit, :update, :complete]
  #before_action :authorize, only: [:edit, :update, :destroy]
  before_action :authorize_admin, only: [:update, :edit]

  def edit
    @birthdays = User.birthdays_this_month.sort_by{|p| p.birth_date.day}
  end

  def create
    @user = User.find(params[:user_id])
    @task = @user.tasks.create(task_params)


    if @task.save
      redirect_to root_path, notice: 'task was successfully created.'
    else
      redirect_to root_path, alert: 'task was not created. Title and text could not be blank'
    end
  end

  #PATCH/user_id/id/
  def complete
    # binding.pry
   @task.update_attribute(:completed, params[:completed])

   params[:completed] == "true" ? (redirect_to root_path, notice: "Todo item completed") : (redirect_to root_path, notice: "Todo item unchecked")
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    if @task.update(task_params)
      redirect_to root_path, notice: 'task was successfully updated.'
    else
      render :edit
    end
  end


  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @task.destroy
    redirect_to root_path, notice: 'task was successfully destroyed.'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @user = User.find(params[:user_id])
    @task = @user.tasks.find(params[:id])

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:title, :text, :priority)
  end

end

homeWork10/todolist/app/controllers/users_controller.rb
class UsersController < ApplicationController
  #wrap_parameters :user, include: [:name, :password, :password_confirmation]
  skip_before_action :require_login, only: [:new, :create]
  #before_action :user_params, only: [:edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:show, :edit]
      def new
          if current_user
            redirect_to root_path, alert: 'You are signed in, logout first.'
          else
            @user = User.new
          end
      end

      def index
        @users = User.all
        @user = current_user
        @birthdays = User.birthdays_this_month.sort_by{|p| p.birth_date.day}
        @first_birthday = User.birthdays_today.first
        #binding.pry
        # if request.referrer == signup_url
        #   redirect_to signup_path
        # end
      end

      def show
        @users = User.all
        @birthdays = User.birthdays_this_month.sort_by{|p| p.birth_date.day}
      end

      def edit
          @user = User.find(params[:id])
          @birthdays = User.birthdays_this_month.sort_by{|p| p.birth_date.day}
      end

      def update
        # binding.pry
        if @user.update(user_params)
          redirect_to root_path, notice: 'Profile was successfully updated.'
        else
          render :edit
        end
      end

      def destroy
         # binding.pry
        @user.destroy
         redirect_to root_url, notice: 'user was successfully destroyed.'
      end

      def create
          #session[:return_to] = nil
          @user = User.new(user_params)
            if @user.save
          session[:user_id] = @user.id
          #redirect_to root_url, notice: "Thank you for signing up!"
          redirect_to root_path , notice: "Thank you for signing up!"
                #binding.pry
        else
          render "new"
        end
      end

    private

      def set_user
        @user = User.find(params[:id])
      end


      def user_params
          params.require(:user).permit(:nickname, :last_name, :first_name, :birth_date, :gender, :provider, :country, :city, :avatar ,:email, :password, :password_confirmation)
      end

end

homeWork10/todolist/app/helpers/application_helper.rb
module ApplicationHelper
end

homeWork10/todolist/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :nickname %><br />
  <%= f.text_field :nickname, class: "form-control" %>
</div>
<% if @user.created_at %>
<div class="form-group">
  <%= f.label :avatar %><br />
  <%= f.file_field :avatar, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name, class: "form-control" %>
</div>


<div class="form-group">
  <%= f.label :gender %><br />
  <%= f.text_field :gender, class: "form-control" %>
</div>
<% end %>
<div class="form-group">
  <%= f.label :email %><br />
  <%= f.email_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :birth_day %><br />
  <%#= f.date_select :birth_date, start_year: 1960, include_blank: true, { :class => "form-control"} %>
  <%= f.date_field :birth_day, as: :date, value: @user.birth_day, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password %><br />
  <%= f.password_field :password, class: "form-control" %>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <% if @user.created_at %>
  <div class="actions"><%= link_to 'Delete User', user_path(current_user), :class=>'btn btn-danger float-lest', method: :delete, data: { confirm: 'Do you want to delete User account. Are you sure?' } %>
    <tr class="actions"><%= f.submit "Update", :class=>'btn btn-default float-right' %></tr></div>
    <% else %>
    <div class="actions"><%= f.submit "Sign Up", :class=>'btn btn-default float-right' %></div>
  </div>
    <% end %>
    <% end %>

homeWork10/todolist/app/views/users/_list.html.erb
<% elements.each do |itm | %>
<% if itm.email != current_user.email %>
  <div class="container-fluid col-sm-14">
    <div class="row card card-default">
      <div class="card-heading col-md-12">
        <strong><%= link_to itm.nickname, itm %></strong> </br>

      </div>
      <div class="row card-body col-md-12">
        <div class="col-md-8 float-left">
          <%= content_tag(:strong, "Nickname: ") + itm.nickname + tag(:br) if itm.nickname? %>
          <%= content_tag(:strong, "Full Name: ") + itm.full_name + tag(:br) if !itm.full_name.blank? %>
          <%= content_tag(:strong, "email: ") + itm.email + tag(:br) if itm.email? %>
          <%= content_tag(:strong, "Age: ") + itm.age.to_s + tag(:br) if itm.birth_date? %>
          <%= content_tag(:strong, "Gender: ") + itm.gender + tag(:br) if itm.gender? %>
          <%= content_tag(:strong, "Phone Number: ") + itm.phone_number + tag(:br) if itm.phone_number? %>
          <%= content_tag(:strong, "Country: ") + itm.country + tag(:br) if itm.country? %>
          <%= content_tag(:strong, "City: ") + itm.city + tag(:br) if itm.city? %>
          <%= content_tag(:strong, "Posts: ") + itm.total_posts.to_s + tag(:br) if itm.total_posts > 0 %>
          <%= content_tag(:strong, "Happy Birthday!") if itm.birthday_today? %>
        </div>
        <div class="col-md-4 float-right">
          <p><%=link_to image_tag(itm.avatar.url, alt: 'Image', :class =>'rounded-circle img-tumbnail img-fluid float-right'), itm if itm.avatar? %></p>
        </div>
      </div><!-- /card-body -->
    </div><!-- /card card-default -->
  </div><!-- /col-sm-5 -->
<% end %>
<%end%>

homeWork10/todolist/app/views/users/edit.html.erb
<center><h3>Editing Profile</h3></center>
  <div class="col-md-8 container-fluid">
    <div class="card card-default">
      <%= render 'form', user: @user %>
    </div>
</div>

homeWork10/todolist/app/views/users/index.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-4 mb-2 white-text text-center text-md-left">
        <div class="card">
          <div class="card-heading">
          </div>

          <div class="card-body">
            <div class="col-md-12">
              <div class="float-center thumb-image">
                <p><%= image_tag(current_user.avatar.url, alt: 'Image', :class =>'d-block mx-auto img-fluid rounded rounded-circle') if current_user.avatar? %></p>
              </div>
            </div>
            <strong>User:</strong>

            <%= current_user.nickname %>
          </br>
          <%= content_tag(:strong, "Nickname: ") + current_user.nickname + tag(:br) if current_user.nickname? %>
          <%= content_tag(:strong, "First Name: ") + current_user.first_name + tag(:br) if current_user.first_name? %>
          <%= content_tag(:strong, "Last Name: ") + current_user.last_name + tag(:br) if current_user.last_name? %>
          <%= content_tag(:strong, "email: ") + current_user.email + tag(:br) if current_user.email? %>
          <%= content_tag(:strong, "Age: ") + current_user.age.to_s + tag(:br) if current_user.birth_day? %>
          <%= content_tag(:strong, "Gender: ") + current_user.gender + tag(:br) if current_user.gender? %>
          <%= content_tag(:strong, "Country: ") + current_user.country + tag(:br) if current_user.country? %>
          <%= content_tag(:strong, "City: ") + current_user.city + tag(:br) if current_user.city? %>
          <%= content_tag(:strong, "Tasks: ") + current_user.total_tasks.to_s + tag(:br) if current_user.total_tasks > 0 %>
          <%= content_tag(:strong, "Unfinished tasks: ") + current_user.uncompleted_tasks.to_s + tag(:br) if current_user.uncompleted_tasks > 0 %>
        </div><!-- /card-body -->


        <tr>
          <td><%= link_to 'Edit', edit_user_path(@user), :class=>'btn btn-light' %></td>
        </tr>

      </div><!-- /card card-default -->

    </div>

    <div class="col-md-12 col-xl-8 mb-6">
      <h3>Create Task</h3>
      <%= render partial: 'tasks/form', :locals => { parent: @user, pl_text: "Task", children: @user.tasks.build } %>
      <h3><%= 'Tasks:' if current_user.tasks.reload.any? %></h3>
      <%= render partial: 'tasks/list', :locals => { elements: current_user.tasks.reload.order('completed'), parent: current_user.reload, post: "task"} %>
    </div>
  </div>
</div>

</div>

homeWork10/todolist/app/views/users/new.html.erb
<%= link_to 'Back', login_url , :class=>'btn btn-default' %>
<center><h1>Sign Up</h1></center>
<div class="card card-body col-md-3 container-fluid">
  <div>
    <%= render 'form' %>
  </div>
</div>

homeWork10/todolist/app/views/users/show.html.erb
<%#= link_to 'New category', categories_path(country_id: @country.id), method: :post, :class=>'btn btn-default' %>
<div class="container">
  <div class="row">
    <div class="col-md-4 mb-2 white-text text-center text-md-left">
      <div class="card">
        <div class="card-heading">
          <%= content_tag(:strong, "Nickname: ") + @user.nickname + tag(:br) if @user.nickname? %>
          <%= content_tag(:strong, "First Name: ") + @user.first_name + tag(:br) if @user.first_name? %>
          <%= content_tag(:strong, "Last Name: ") + @user.last_name + tag(:br) if @user.last_name? %>
          <%= content_tag(:strong, "Full Name: ") + @user.full_name + tag(:br) if !@user.full_name.blank? %>
          <%= content_tag(:strong, "email: ") + @user.email + tag(:br) if @user.email? %>
          <%= content_tag(:strong, "Age: ") + @user.age.to_s + tag(:br) if @user.birth_day? %>
          <%= content_tag(:strong, "Gender: ") + @user.gender + tag(:br) if @user.gender? %>
          <%= content_tag(:strong, "Phone Number: ") + @user.phone_number + tag(:br) if @user.phone_number? %>
          <%= content_tag(:strong, "Country: ") + @user.country + tag(:br) if @user.country? %>
          <%= content_tag(:strong, "City: ") + @user.city + tag(:br) if @user.city? %>
          <%= content_tag(:strong, "Posts: ") + @user.total_posts.to_s + tag(:br) if @user.total_posts > 0 %>
        </div>
        <div class="card-body">
          <div class="col-md-12">
            <div class="float-left col-md-4 col-xs-12 thumb-image">
              <p><%= image_tag(@user.avatar.url, alt: 'Image', :class =>'rounded-circle img-tumbnail img-fluid float-right') if @user.avatar? %></p>
            </div>
          </div>
        </div><!-- /card-body -->


          <tr>
            <td><%= link_to 'Edit', edit_user_path(@user), :class=>'btn btn-light' %></td>
            <td><%= link_to 'Delete', user_path(@user), :class=>'btn btn-danger float-right', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>


      </div><!-- /card card-default -->
      <%= render partial: 'list', :locals => { elements: @users} %>
      <td><%= link_to 'Back', root_path , :class=>'btn btn-light' %></td>
    </div>

    <div class="col-md-8 col-xl-5 mb-4">

      <h3>Create Task</h3>
      <%= render partial: 'posts/form', :locals => { parent: @user, pl_text: "Task", children: @user.tasks.build } %>
      <h3><%= 'Tasks:' if @user.tasks.reload.any? %></h3>
      <%= render partial: 'posts/list', :locals => { elements: @user.tasks.reload, parent: @user} %>

    </div>
  </div>
</div>