homeWork4/warehouse/config/routes.rb
Rails.application.routes.draw do

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users
  resources :sessions , except: [:edit, :update]
  resources :stores
  resources :categories
  resources :products
  resources :suppliers
  resources :vendors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stores#index'
end

homeWork4/warehouse/app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :supplier
  validates_uniqueness_of :name
end

homeWork4/warehouse/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendores/1
  # GET /vendores/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
      #  format.html { redirect_to @vendor, notice: 'vendor was successfully created.' }
        format.html { redirect_to supplier_path(@vendor.supplier.id) }
      #  format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
      #  format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to supplier_path(@vendor.supplier.id), notice: 'vendor was successfully updated.' }
      #  format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
      #  format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to supplier_path(@vendor.supplier.id), notice: 'vendor was successfully destroyed.' }
    #  format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :image, :supplier_id)
    end
end

homeWork4/warehouse/app/helpers/vendors_helper.rb
module VendorsHelper
end

homeWork4/warehouse/app/views/vendors/_form.html.erb
<%= form_with model: @vendor, local: true do |form| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="container">
    <div class="col-sm-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%#= form.label :name %>

          <%= form.text_field :name , class: 'input-block-level', autofocus: true, placeholder: 'Vendor name' %>
        </div>

      <div class="panel-body">
        <div class="col-md-12">
            <%= form.label :image %>
            <%=  form.file_field :image  %>
            <%= form.hidden_field :supplier_id %>
          </div>
              <div class="container-fluid">
                 <div class="actions">
                      <%= form.submit  class: 'btn btn-default' %>
                </div>
              </div>
          </div>
        </div>
      </div>
  </div>
</div>
<% end %>

homeWork4/warehouse/app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

homeWork4/warehouse/app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', :back, :class=>'btn btn-default'  %>

homeWork4/warehouse/app/views/vendors/show.html.erb
  <div class="container">
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-heading">
          <strong>Vendors:</strong>
          <%= @vendor.name %>
      </div>
      <div class="panel-body">
        <div class="col-md-12">
          <div class="pull-left col-md-4 col-xs-12 thumb-image">
              <p><%= image_tag(@vendor.image.url, alt: 'Image', :class =>'center-block img-responsive') if @vendor.image? %></p>
          </div>
        </div>

      <tr class="container-fluid">
        <% if current_user %>
              <td><%= link_to 'Edit', edit_vendor_path(@vendor), :class=>'btn btn-default' %></td>
              <td><%= link_to 'Delete', vendor_path(@vendor), :class=>'btn btn-danger  pull-right', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    </div><!-- /panel-body -->
</div><!-- /panel panel-default -->
<!-- /col-sm-5 -->
<td><%= link_to 'Back', supplier_path(@vendor.supplier.id) , :class=>'btn btn-default' %></td>


</div>
</div>