homeWork4/warehouse/config/routes.rb
Rails.application.routes.draw do

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users
  resources :sessions , except: [:edit, :update]
  resources :stores
  resources :categories
  resources :products
  resources :suppliers
  resources :vendors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stores#index'
end

homeWork4/warehouse/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Werhouse</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<header>
  <nav>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li> <%= link_to "Home", root_url %> </li>
            <li> <%= link_to 'Manage Users', users_path if current_user %> </li>
          </ul>


          <% if current_user %>

          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text">   Logged in as <b> <%= current_user.name %></b>.</p>
            <li> <%= link_to "Log Out", logout_path %> </li>
          </ul>
          <% else %>
          <ul class="nav navbar-nav navbar-left">
            <li> <%= link_to "Sign Up", signup_path %> </li>
            <li> <%#= link_to "Log In", login_path %> </li>
          </ul>
          <div class="nav navbar-nav navbar-right">
            <%= render 'sessions/nav_form' %>
          </div>
          <% end %>

        </div>
      </div>
    </div>
  </nav>
</header>
<body class='container'>
  <% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>
  <%= yield %>
</body>

<footer>
  <div class="navbar-fixed-bottom row-fluid">
    <div class="navbar-inner">
      <div class="container text-center">
        -=pVa=- 2018
      </div>
    </div>
  </div>
</footer>

</html>